name: check

# Controls when the workflow will run
on: push

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.x
          opam-disable-sandboxing: true
          dune-cache: true

      - name: "Install dependencies"
        run: opam exec -- opam install . --deps-only --with-test

      - name: "Build application"
        run: opam exec -- dune build

      - name: "Run tests"
        run: opam exec -- dune runtest

  lint-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v5

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.x
          opam-disable-sandboxing: true
          dune-cache: true

      - uses: ocaml/setup-ocaml/lint-fmt@v3
