name: check

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.x
          opam-disable-sandboxing: true
          dune-cache: true

      - name: "Install dependencies"
        run: opam install . --deps-only --with-test ocamlformat=0.27.0 --yes

      - name: "Check formatting"
        run: opam exec -- dune fmt --auto-promote && git diff --exit-code

      - name: "Build application"
        run: opam exec -- dune build

      - name: "Run tests"
        run: opam exec -- dune runtest
