name: check

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.x
          opam-disable-sandboxing: true
          dune-cache: true

      - name: "Install dependencies"
        run: opam exec -- opam install . --deps-only --with-test

      - name: "Install ocamlformat"
        run: opam exec -- opam install ocamlformat.0.27.0

      - name: "Check formatting"
        run: opam exec -- dune build @fmt

      - name: "Build application"
        run: opam exec -- dune build --verbose

      - name: "Run tests"
        run: opam exec -- dune runtest
